### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [mssumanth/jamming#5]
(Exceeds Expectations)

Well done on this feature request! I agree that including an audio preview of the track is an essential part of a music playlist app. 

Nice work actually implementing the feature as well! Good job noticing that you could get the `preview_url` from the same endpoint that you're fetching the other track information. Feel free to look further at this [endpoint](https://developer.spotify.com/documentation/web-api/reference/search/search/) and see what other info you could add. (_For example, adding the album cover image could add a nice visual element to the app!_)

Your feature request documentation is also very well-written and thorough. I like how you've given thought to not only the functionality of the feature, but also the overall design and user experience! 
 
And lastly, as a further challenge, feel free to continue to explore the [Spotify API](https://developer.spotify.com/documentation/web-api/reference/) and see if you're able to add more features to this app. Then, practice writing a feature request for it. Have fun! :)

**Comment by mssumanth** [comment]
ThankYou :) Will work on improving my skills as per your suggestion.

Best Regards
Sumanth
